import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "../components/PageHero";

export const metadata: Metadata = { title: "Software & Apps", description: "Explore software products created by Techpsyco, including Paycore and the company’s growing portfolio of useful digital platforms.", alternates: { canonical: "/software" } };

export default function SoftwarePage() {
  const softwareSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Paycore", applicationCategory: "FinanceApplication", operatingSystem: "Web", creator: { "@type": "Organization", name: "Techpsyco" }, description: "A digital finance product designed to simplify everyday money operations." };
  return <main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }} /><PageHero eyebrow="Software by Techpsyco" title="Useful products, built to solve real problems." text="A growing portfolio of software created and operated by Techpsyco to make important work and everyday life clearer, faster and easier to manage." />
    <section className="section section-compact"><div className="container product-catalogue">
      <article className="software-feature" id="paycore"><div className="software-visual"><span className="product-icon product-icon-large">P</span><span className="status">Product preview</span></div><div><p className="eyebrow">Finance software</p><h2>Paycore</h2><p className="lead-sm">A focused digital finance product created to make everyday money operations easier to understand and manage.</p><div className="tag-row"><span>Web app</span><span>Finance</span><span>Responsive</span></div><div className="actions"><a className="button" href="mailto:hello@techpsyco.com?subject=Paycore%20access">Request access</a><a className="text-link" href="mailto:hello@techpsyco.com?subject=Paycore%20download">Ask about download →</a></div></div></article>
      <div className="catalogue-note"><div><p className="eyebrow">More releases</p><h2>New products are being prepared.</h2></div><p>Techpsyco is building a growing portfolio of useful software. New product links and downloads will appear here as each release becomes available.</p></div>
      <div className="solution-grid"><article><span>01</span><h3>Financial platforms</h3><p>Accessible products that make money operations clearer, safer and easier to manage.</p></article><article><span>02</span><h3>Operations software</h3><p>Purposeful products that simplify repeatable work and improve everyday visibility.</p></article><article><span>03</span><h3>Automation products</h3><p>Focused tools that connect services, information and intelligent workflows.</p></article></div>
    </div></section><section className="cta-section"><div className="container cta-box"><div><p className="eyebrow">Building what comes next</p><h2>Follow Techpsyco as our software portfolio continues to grow.</h2></div><Link className="button button-light" href="/contact">Product enquiries</Link></div></section></main>;
}
